[project]
name = "python"
version = "0.1.0"
description = "Example for inpainting using this package."
requires-python = ">=3.9"
dependencies = [
    "inpaint",
    "pillow>=11.3.0",
]

[tool.uv.sources]
inpaint = { workspace = true }
